POST http://localhost:3000/api/trucks
Content-Type: application/json

{
    "model": "BMWw",
    "license_plate": "QJK4A97",
    "year": "2024",
    "operation_status": "available"
}

###

GET http://localhost:3000/api/trucks?search=

###

PUT http://localhost:3000/api/trucks/1
Content-Type: application/json

{
    "model": "BMW X20",
    "license_plate": "QJK4A94",
    "year": "2035",
    "operation_status": "coming_soon"
}

###

DELETE http://localhost:3000/api/trucks/5
